// 80+ recettes d'applications pour Orbit
export const recipes = {
  // Communication
  gmail: {
    id: 'gmail',
    name: 'Gmail',
    url: 'https://mail.google.com',
    icon: '📧',
    color: '#EA4335',
    category: 'communication',
    // Icône de marque officielle Google (les favicons .google.com sont tous
    // le même « G » générique → Drive, Gmail, Docs se ressembleraient)
    brandIcon: 'https://ssl.gstatic.com/images/branding/product/2x/gmail_2020q4_48dp.png',
  },
  outlook: {
    id: 'outlook',
    name: 'Outlook',
    url: 'https://outlook.live.com/mail',
    icon: '📨',
    color: '#0078D4',
    category: 'communication',
  },
  slack: {
    id: 'slack',
    name: 'Slack',
    url: 'https://app.slack.com',
    icon: '💬',
    color: '#4A154B',
    category: 'communication',
  },
  discord: {
    id: 'discord',
    name: 'Discord',
    url: 'https://discord.com/app',
    icon: '🎮',
    color: '#5865F2',
    category: 'communication',
  },
  telegram: {
    id: 'telegram',
    name: 'Telegram',
    url: 'https://web.telegram.org',
    icon: '✈️',
    color: '#0088CC',
    category: 'communication',
  },
  whatsapp: {
    id: 'whatsapp',
    name: 'WhatsApp',
    url: 'https://web.whatsapp.com',
    icon: '💚',
    color: '#25D366',
    category: 'communication',
  },
  messenger: {
    id: 'messenger',
    name: 'Messenger',
    url: 'https://www.messenger.com',
    icon: '💙',
    color: '#0084FF',
    category: 'communication',
  },
  teams: {
    id: 'teams',
    name: 'Microsoft Teams',
    url: 'https://teams.microsoft.com',
    icon: '👥',
    color: '#6264A7',
    category: 'communication',
  },
  zoom: {
    id: 'zoom',
    name: 'Zoom',
    url: 'https://zoom.us',
    icon: '📹',
    color: '#2D8CFF',
    category: 'communication',
  },

  // Productivité
  notion: {
    id: 'notion',
    name: 'Notion',
    url: 'https://notion.so',
    icon: '📝',
    color: '#000000',
    category: 'productivity',
  },
  todoist: {
    id: 'todoist',
    name: 'Todoist',
    url: 'https://todoist.com/app',
    icon: '✅',
    color: '#E44332',
    category: 'productivity',
  },
  trello: {
    id: 'trello',
    name: 'Trello',
    url: 'https://trello.com',
    icon: '📋',
    color: '#0079BF',
    category: 'productivity',
  },
  asana: {
    id: 'asana',
    name: 'Asana',
    url: 'https://app.asana.com',
    icon: '🎯',
    color: '#F06A6A',
    category: 'productivity',
  },
  monday: {
    id: 'monday',
    name: 'Monday',
    url: 'https://monday.com',
    icon: '📊',
    color: '#FF3D57',
    category: 'productivity',
  },
  clickup: {
    id: 'clickup',
    name: 'ClickUp',
    url: 'https://app.clickup.com',
    icon: '🚀',
    color: '#7B68EE',
    category: 'productivity',
  },
  airtable: {
    id: 'airtable',
    name: 'Airtable',
    url: 'https://airtable.com',
    icon: '📐',
    color: '#18BFFF',
    category: 'productivity',
  },

  // Développement
  github: {
    id: 'github',
    name: 'GitHub',
    url: 'https://github.com',
    icon: '🐙',
    color: '#181717',
    category: 'development',
  },
  gitlab: {
    id: 'gitlab',
    name: 'GitLab',
    url: 'https://gitlab.com',
    icon: '🦊',
    color: '#FC6D26',
    category: 'development',
  },
  linear: {
    id: 'linear',
    name: 'Linear',
    url: 'https://linear.app',
    icon: '⚡',
    color: '#5E6AD2',
    category: 'development',
  },
  jira: {
    id: 'jira',
    name: 'Jira',
    url: 'https://atlassian.net',
    icon: '🔷',
    color: '#0052CC',
    category: 'development',
  },
  figma: {
    id: 'figma',
    name: 'Figma',
    url: 'https://figma.com',
    icon: '🎨',
    color: '#F24E1E',
    category: 'development',
  },
  vercel: {
    id: 'vercel',
    name: 'Vercel',
    url: 'https://vercel.com',
    icon: '▲',
    color: '#000000',
    category: 'development',
  },
  netlify: {
    id: 'netlify',
    name: 'Netlify',
    url: 'https://app.netlify.com',
    icon: '🌐',
    color: '#00C7B7',
    category: 'development',
  },

  // IA & Chat
  chatgpt: {
    id: 'chatgpt',
    name: 'ChatGPT',
    url: 'https://chat.openai.com',
    icon: '🤖',
    color: '#10A37F',
    category: 'ai',
  },
  claude: {
    id: 'claude',
    name: 'Claude',
    url: 'https://claude.ai',
    icon: '🧠',
    color: '#D97757',
    category: 'ai',
  },
  gemini: {
    id: 'gemini',
    name: 'Gemini',
    url: 'https://gemini.google.com',
    icon: '✨',
    color: '#8E75FF',
    category: 'ai',
  },
  perplexity: {
    id: 'perplexity',
    name: 'Perplexity',
    url: 'https://perplexity.ai',
    icon: '🔍',
    color: '#20808D',
    category: 'ai',
  },

  // Réseaux sociaux
  twitter: {
    id: 'twitter',
    name: 'X (Twitter)',
    url: 'https://x.com',
    icon: '𝕏',
    color: '#000000',
    category: 'social',
  },
  linkedin: {
    id: 'linkedin',
    name: 'LinkedIn',
    url: 'https://linkedin.com',
    icon: '💼',
    color: '#0A66C2',
    category: 'social',
  },
  facebook: {
    id: 'facebook',
    name: 'Facebook',
    url: 'https://facebook.com',
    icon: '📘',
    color: '#1877F2',
    category: 'social',
  },
  instagram: {
    id: 'instagram',
    name: 'Instagram',
    url: 'https://instagram.com',
    icon: '📸',
    color: '#E4405F',
    category: 'social',
  },
  reddit: {
    id: 'reddit',
    name: 'Reddit',
    url: 'https://reddit.com',
    icon: '🤖',
    color: '#FF4500',
    category: 'social',
  },
  mastodon: {
    id: 'mastodon',
    name: 'Mastodon',
    url: 'https://mastodon.social',
    icon: '🐘',
    color: '#6364FF',
    category: 'social',
  },

  // Cloud & Storage
  gdrive: {
    id: 'gdrive',
    name: 'Google Drive',
    url: 'https://drive.google.com',
    icon: '💾',
    color: '#4285F4',
    category: 'cloud',
    brandIcon: 'https://ssl.gstatic.com/images/branding/product/2x/drive_2020q4_48dp.png',
  },
  dropbox: {
    id: 'dropbox',
    name: 'Dropbox',
    url: 'https://dropbox.com',
    icon: '📦',
    color: '#0061FF',
    category: 'cloud',
  },
  onedrive: {
    id: 'onedrive',
    name: 'OneDrive',
    url: 'https://onedrive.live.com',
    icon: '☁️',
    color: '#0078D4',
    category: 'cloud',
  },

  // Média & Divertissement
  youtube: {
    id: 'youtube',
    name: 'YouTube',
    url: 'https://youtube.com',
    icon: '▶️',
    color: '#FF0000',
    category: 'media',
  },
  // Musique
  spotify: {
    id: 'spotify',
    name: 'Spotify',
    url: 'https://open.spotify.com',
    icon: '🎵',
    color: '#1DB954',
    category: 'music',
  },
  ytmusic: {
    id: 'ytmusic',
    name: 'YouTube Music',
    url: 'https://music.youtube.com',
    icon: '🎶',
    color: '#FF0000',
    category: 'music',
  },
  deezer: {
    id: 'deezer',
    name: 'Deezer',
    url: 'https://www.deezer.com',
    icon: '🎧',
    color: '#A238FF',
    category: 'music',
  },
  appleMusic: {
    id: 'appleMusic',
    name: 'Apple Music',
    url: 'https://music.apple.com',
    icon: '🍎',
    color: '#FA243C',
    category: 'music',
  },
  amazonMusic: {
    id: 'amazonMusic',
    name: 'Amazon Music',
    url: 'https://music.amazon.com',
    icon: '🎼',
    color: '#00A8E1',
    category: 'music',
  },
  tidal: {
    id: 'tidal',
    name: 'Tidal',
    url: 'https://listen.tidal.com',
    icon: '🌊',
    color: '#000000',
    category: 'music',
  },
  qobuz: {
    id: 'qobuz',
    name: 'Qobuz',
    url: 'https://play.qobuz.com',
    icon: '🎚️',
    color: '#0070D8',
    category: 'music',
  },
  soundcloud: {
    id: 'soundcloud',
    name: 'SoundCloud',
    url: 'https://soundcloud.com',
    icon: '🔊',
    color: '#FF5500',
    category: 'music',
  },
  bandcamp: {
    id: 'bandcamp',
    name: 'Bandcamp',
    url: 'https://bandcamp.com',
    icon: '🎸',
    color: '#629AA9',
    category: 'music',
  },
  twitch: {
    id: 'twitch',
    name: 'Twitch',
    url: 'https://twitch.tv',
    icon: '🎮',
    color: '#9146FF',
    category: 'media',
  },
  netflix: {
    id: 'netflix',
    name: 'Netflix',
    url: 'https://netflix.com',
    icon: '🍿',
    color: '#E50914',
    category: 'media',
  },

  // Éducation & Référence
  wikipedia: {
    id: 'wikipedia',
    name: 'Wikipedia',
    url: 'https://wikipedia.org',
    icon: '📚',
    color: '#000000',
    category: 'reference',
  },
  stackoverflow: {
    id: 'stackoverflow',
    name: 'Stack Overflow',
    url: 'https://stackoverflow.com',
    icon: '💡',
    color: '#F58025',
    category: 'reference',
  },
  medium: {
    id: 'medium',
    name: 'Medium',
    url: 'https://medium.com',
    icon: '📖',
    color: '#000000',
    category: 'reference',
  },
  devto: {
    id: 'devto',
    name: 'DEV Community',
    url: 'https://dev.to',
    icon: '👩💻',
    color: '#0A0A0A',
    category: 'reference',
  },

  // Finance
  stripe: {
    id: 'stripe',
    name: 'Stripe',
    url: 'https://dashboard.stripe.com',
    icon: '💳',
    color: '#635BFF',
    category: 'finance',
  },
  paypal: {
    id: 'paypal',
    name: 'PayPal',
    url: 'https://paypal.com',
    icon: '💰',
    color: '#00457C',
    category: 'finance',
  },

  // Analytics
  analytics: {
    id: 'analytics',
    name: 'Google Analytics',
    url: 'https://analytics.google.com',
    icon: '📈',
    color: '#F9AB00',
    category: 'analytics',
  },
  plausible: {
    id: 'plausible',
    name: 'Plausible',
    url: 'https://plausible.io',
    icon: '📊',
    color: '#5850EC',
    category: 'analytics',
  },

  // CRM
  hubspot: {
    id: 'hubspot',
    name: 'HubSpot',
    url: 'https://app.hubspot.com',
    icon: '🎯',
    color: '#FF7A59',
    category: 'crm',
  },
  salesforce: {
    id: 'salesforce',
    name: 'Salesforce',
    url: 'https://salesforce.com',
    icon: '☁️',
    color: '#00A1E0',
    category: 'crm',
  },

  // Autres
  calendly: {
    id: 'calendly',
    name: 'Calendly',
    url: 'https://calendly.com',
    icon: '📅',
    color: '#006BFF',
    category: 'productivity',
  },
  miro: {
    id: 'miro',
    name: 'Miro',
    url: 'https://miro.com',
    icon: '🎨',
    color: '#FFD02F',
    category: 'productivity',
  },
  canva: {
    id: 'canva',
    name: 'Canva',
    url: 'https://canva.com',
    icon: '🖼️',
    color: '#00C4CC',
    category: 'design',
  },
};

export const categories = {
  communication: { name: 'Communication', icon: '💬', color: '#6366f1' },
  productivity: { name: 'Productivité', icon: '⚡', color: '#10b981' },
  development: { name: 'Développement', icon: '💻', color: '#8b5cf6' },
  ai: { name: 'IA & Chat', icon: '🤖', color: '#ec4899' },
  social: { name: 'Réseaux sociaux', icon: '🌐', color: '#3b82f6' },
  cloud: { name: 'Cloud & Storage', icon: '☁️', color: '#06b6d4' },
  music: { name: 'Musique', icon: '🎵', color: '#1DB954' },
  media: { name: 'Vidéo & Streaming', icon: '🎬', color: '#f59e0b' },
  reference: { name: 'Référence', icon: '📚', color: '#6b7280' },
  finance: { name: 'Finance', icon: '💰', color: '#14b8a6' },
  analytics: { name: 'Analytics', icon: '📊', color: '#a855f7' },
  crm: { name: 'CRM', icon: '🎯', color: '#ef4444' },
  design: { name: 'Design', icon: '🎨', color: '#f97316' },
};
