// 80+ recettes d'applications pour Orbit
export const recipes = {
  // Communication
  gmail: {
    id: 'gmail',
    name: 'Gmail',
    url: 'https://mail.google.com',
    icon: '📧',
    color: '#EA4335',
    category: 'communication',
    // Icône de marque officielle Google (les favicons .google.com sont tous
    // le même « G » générique → Drive, Gmail, Docs se ressembleraient)
    brandIcon: 'https://ssl.gstatic.com/images/branding/product/2x/gmail_2020q4_48dp.png',
  },
  outlook: {
    id: 'outlook',
    name: 'Outlook',
    url: 'https://outlook.live.com/mail',
    icon: '📨',
    color: '#0078D4',
    category: 'communication',
  },
  slack: {
    id: 'slack',
    name: 'Slack',
    url: 'https://app.slack.com',
    icon: '💬',
    color: '#4A154B',
    category: 'communication',
  },
  discord: {
    id: 'discord',
    name: 'Discord',
    url: 'https://discord.com/app',
    icon: '🎮',
    color: '#5865F2',
    category: 'communication',
  },
  telegram: {
    id: 'telegram',
    name: 'Telegram',
    url: 'https://web.telegram.org',
    icon: '✈️',
    color: '#0088CC',
    category: 'communication',
  },
  whatsapp: {
    id: 'whatsapp',
    name: 'WhatsApp',
    url: 'https://web.whatsapp.com',
    icon: '💚',
    color: '#25D366',
    category: 'communication',
  },
  messenger: {
    id: 'messenger',
    name: 'Messenger',
    url: 'https://www.messenger.com',
    icon: '💙',
    color: '#0084FF',
    category: 'communication',
  },
  teams: {
    id: 'teams',
    name: 'Microsoft Teams',
    url: 'https://teams.microsoft.com',
    icon: '👥',
    color: '#6264A7',
    category: 'communication',
  },
  meet: {
    id: 'meet',
    name: 'Google Meet',
    url: 'https://meet.google.com',
    icon: '📹',
    color: '#00897B',
    category: 'communication',
    brandIcon: 'https://ssl.gstatic.com/images/branding/product/2x/meet_2020q4_48dp.png',
  },
  chat: {
    id: 'chat',
    name: 'Google Chat',
    url: 'https://chat.google.com',
    icon: '💭',
    color: '#2D7FF9',
    category: 'communication',
    brandIcon: 'https://ssl.gstatic.com/images/branding/product/2x/chat_2020q4_48dp.png',
  },
  zoom: {
    id: 'zoom',
    name: 'Zoom',
    url: 'https://zoom.us',
    icon: '📹',
    color: '#2D8CFF',
    category: 'communication',
  },

  // Productivité
  keep: {
    id: 'keep',
    name: 'Google Keep',
    url: 'https://keep.google.com',
    icon: '🗒️',
    color: '#FFBA00',
    category: 'productivity',
    brandIcon: 'https://ssl.gstatic.com/images/branding/product/2x/keep_2020q4_48dp.png',
  },
  calendar: {
    id: 'calendar',
    name: 'Google Calendar',
    url: 'https://calendar.google.com',
    icon: '📅',
    color: '#4285F4',
    category: 'productivity',
    brandIcon: 'https://ssl.gstatic.com/images/branding/product/2x/calendar_2020q4_48dp.png',
  },
  docs: {
    id: 'docs',
    name: 'Google Docs',
    url: 'https://docs.google.com',
    icon: '📄',
    color: '#4285F4',
    category: 'productivity',
    brandIcon: 'https://ssl.gstatic.com/images/branding/product/2x/docs_2020q4_48dp.png',
  },
  sheets: {
    id: 'sheets',
    name: 'Google Sheets',
    url: 'https://sheets.google.com',
    icon: '📗',
    color: '#34A853',
    category: 'productivity',
    brandIcon: 'https://ssl.gstatic.com/images/branding/product/2x/sheets_2020q4_48dp.png',
  },
  slides: {
    id: 'slides',
    name: 'Google Slides',
    url: 'https://slides.google.com',
    icon: '📽️',
    color: '#FBBC04',
    category: 'productivity',
    brandIcon: 'https://ssl.gstatic.com/images/branding/product/2x/slides_2020q4_48dp.png',
  },
  tasks: {
    id: 'tasks',
    name: 'Google Tasks',
    url: 'https://tasks.google.com',
    icon: '☑️',
    color: '#4285F4',
    category: 'productivity',
    brandIcon: 'https://ssl.gstatic.com/images/branding/product/2x/tasks_48dp.png',
  },
  contacts: {
    id: 'contacts',
    name: 'Google Contacts',
    url: 'https://contacts.google.com',
    icon: '👤',
    color: '#4285F4',
    category: 'productivity',
    brandIcon: 'https://ssl.gstatic.com/images/branding/product/2x/contacts_48dp.png',
  },
  notion: {
    id: 'notion',
    name: 'Notion',
    url: 'https://notion.so',
    icon: '📝',
    color: '#000000',
    category: 'productivity',
  },
  todoist: {
    id: 'todoist',
    name: 'Todoist',
    url: 'https://todoist.com/app',
    icon: '✅',
    color: '#E44332',
    category: 'productivity',
  },
  trello: {
    id: 'trello',
    name: 'Trello',
    url: 'https://trello.com',
    icon: '📋',
    color: '#0079BF',
    category: 'productivity',
  },
  asana: {
    id: 'asana',
    name: 'Asana',
    url: 'https://app.asana.com',
    icon: '🎯',
    color: '#F06A6A',
    category: 'productivity',
  },
  monday: {
    id: 'monday',
    name: 'Monday',
    url: 'https://monday.com',
    icon: '📊',
    color: '#FF3D57',
    category: 'productivity',
  },
  clickup: {
    id: 'clickup',
    name: 'ClickUp',
    url: 'https://app.clickup.com',
    icon: '🚀',
    color: '#7B68EE',
    category: 'productivity',
  },
  airtable: {
    id: 'airtable',
    name: 'Airtable',
    url: 'https://airtable.com',
    icon: '📐',
    color: '#18BFFF',
    category: 'productivity',
  },

  // Développement
  github: {
    id: 'github',
    name: 'GitHub',
    url: 'https://github.com',
    icon: '🐙',
    color: '#181717',
    category: 'development',
  },
  gitlab: {
    id: 'gitlab',
    name: 'GitLab',
    url: 'https://gitlab.com',
    icon: '🦊',
    color: '#FC6D26',
    category: 'development',
  },
  linear: {
    id: 'linear',
    name: 'Linear',
    url: 'https://linear.app',
    icon: '⚡',
    color: '#5E6AD2',
    category: 'development',
  },
  jira: {
    id: 'jira',
    name: 'Jira',
    url: 'https://atlassian.net',
    icon: '🔷',
    color: '#0052CC',
    category: 'development',
  },
  figma: {
    id: 'figma',
    name: 'Figma',
    url: 'https://figma.com',
    icon: '🎨',
    color: '#F24E1E',
    category: 'development',
  },
  vercel: {
    id: 'vercel',
    name: 'Vercel',
    url: 'https://vercel.com',
    icon: '▲',
    color: '#000000',
    category: 'development',
  },
  netlify: {
    id: 'netlify',
    name: 'Netlify',
    url: 'https://app.netlify.com',
    icon: '🌐',
    color: '#00C7B7',
    category: 'development',
  },

  // IA & Chat
  chatgpt: {
    id: 'chatgpt',
    name: 'ChatGPT',
    url: 'https://chat.openai.com',
    icon: '🤖',
    color: '#10A37F',
    category: 'ai',
  },
  claude: {
    id: 'claude',
    name: 'Claude',
    url: 'https://claude.ai',
    icon: '🧠',
    color: '#D97757',
    category: 'ai',
  },
  gemini: {
    id: 'gemini',
    name: 'Gemini',
    url: 'https://gemini.google.com',
    icon: '✨',
    color: '#8E75FF',
    category: 'ai',
  },
  perplexity: {
    id: 'perplexity',
    name: 'Perplexity',
    url: 'https://perplexity.ai',
    icon: '🔍',
    color: '#20808D',
    category: 'ai',
  },
  copilot: {
    id: 'copilot',
    name: 'Microsoft Copilot',
    url: 'https://copilot.microsoft.com',
    icon: '🟦',
    color: '#0078D4',
    category: 'ai',
  },
  mistral: {
    id: 'mistral',
    name: 'Le Chat (Mistral)',
    url: 'https://chat.mistral.ai',
    icon: '🐱',
    color: '#FA520F',
    category: 'ai',
  },
  grok: {
    id: 'grok',
    name: 'Grok',
    url: 'https://grok.com',
    icon: '⚡',
    color: '#000000',
    category: 'ai',
  },
  metaai: {
    id: 'metaai',
    name: 'Meta AI',
    url: 'https://www.meta.ai',
    icon: '♾️',
    color: '#0866FF',
    category: 'ai',
  },
  poe: {
    id: 'poe',
    name: 'Poe',
    url: 'https://poe.com',
    icon: '🎭',
    color: '#5D5CDE',
    category: 'ai',
  },
  huggingchat: {
    id: 'huggingchat',
    name: 'HuggingChat',
    url: 'https://huggingface.co/chat',
    icon: '🤗',
    color: '#FFD21E',
    category: 'ai',
  },
  notebooklm: {
    id: 'notebooklm',
    name: 'NotebookLM',
    url: 'https://notebooklm.google.com',
    icon: '📓',
    color: '#4285F4',
    category: 'ai',
  },
  // IA asiatiques
  deepseek: {
    id: 'deepseek',
    name: 'DeepSeek',
    url: 'https://chat.deepseek.com',
    icon: '🐋',
    color: '#4D6BFE',
    category: 'ai',
  },
  qwen: {
    id: 'qwen',
    name: 'Qwen (Tongyi)',
    url: 'https://chat.qwen.ai',
    icon: '🌐',
    color: '#615CED',
    category: 'ai',
  },
  kimi: {
    id: 'kimi',
    name: 'Kimi',
    url: 'https://kimi.moonshot.cn',
    icon: '🌙',
    color: '#101010',
    category: 'ai',
  },
  doubao: {
    id: 'doubao',
    name: 'Doubao',
    url: 'https://www.doubao.com',
    icon: '🫧',
    color: '#3B7CFF',
    category: 'ai',
  },
  yiyan: {
    id: 'yiyan',
    name: 'ERNIE Bot (文心一言)',
    url: 'https://yiyan.baidu.com',
    icon: '🐻',
    color: '#4E6EF2',
    category: 'ai',
  },
  chatglm: {
    id: 'chatglm',
    name: 'ChatGLM (智谱清言)',
    url: 'https://chatglm.cn',
    icon: '🧩',
    color: '#3859FF',
    category: 'ai',
  },
  yuanbao: {
    id: 'yuanbao',
    name: 'Tencent Yuanbao',
    url: 'https://yuanbao.tencent.com',
    icon: '🐧',
    color: '#0052D9',
    category: 'ai',
  },
  clovax: {
    id: 'clovax',
    name: 'CLOVA X',
    url: 'https://clova-x.naver.com',
    icon: '🟢',
    color: '#03C75A',
    category: 'ai',
  },
  felo: {
    id: 'felo',
    name: 'Felo',
    url: 'https://felo.ai',
    icon: '🔮',
    color: '#6C4BF6',
    category: 'ai',
  },

  // Réseaux sociaux
  twitter: {
    id: 'twitter',
    name: 'X (Twitter)',
    url: 'https://x.com',
    icon: '𝕏',
    color: '#000000',
    category: 'social',
  },
  linkedin: {
    id: 'linkedin',
    name: 'LinkedIn',
    url: 'https://linkedin.com',
    icon: '💼',
    color: '#0A66C2',
    category: 'social',
  },
  facebook: {
    id: 'facebook',
    name: 'Facebook',
    url: 'https://facebook.com',
    icon: '📘',
    color: '#1877F2',
    category: 'social',
  },
  instagram: {
    id: 'instagram',
    name: 'Instagram',
    url: 'https://instagram.com',
    icon: '📸',
    color: '#E4405F',
    category: 'social',
  },
  reddit: {
    id: 'reddit',
    name: 'Reddit',
    url: 'https://reddit.com',
    icon: '🤖',
    color: '#FF4500',
    category: 'social',
  },
  mastodon: {
    id: 'mastodon',
    name: 'Mastodon',
    url: 'https://mastodon.social',
    icon: '🐘',
    color: '#6364FF',
    category: 'social',
  },

  // Cloud & Storage
  gdrive: {
    id: 'gdrive',
    name: 'Google Drive',
    url: 'https://drive.google.com',
    icon: '💾',
    color: '#4285F4',
    category: 'cloud',
    brandIcon: 'https://ssl.gstatic.com/images/branding/product/2x/drive_2020q4_48dp.png',
  },
  photos: {
    id: 'photos',
    name: 'Google Photos',
    url: 'https://photos.google.com',
    icon: '🖼️',
    color: '#EA4335',
    category: 'cloud',
    brandIcon: 'https://ssl.gstatic.com/images/branding/product/2x/photos_48dp.png',
  },
  one: {
    id: 'one',
    name: 'Google One',
    url: 'https://one.google.com',
    icon: '🗄️',
    color: '#4285F4',
    category: 'cloud',
    brandIcon: 'https://ssl.gstatic.com/images/branding/product/2x/one_48dp.png',
  },
  dropbox: {
    id: 'dropbox',
    name: 'Dropbox',
    url: 'https://dropbox.com',
    icon: '📦',
    color: '#0061FF',
    category: 'cloud',
  },
  onedrive: {
    id: 'onedrive',
    name: 'OneDrive',
    url: 'https://onedrive.live.com',
    icon: '☁️',
    color: '#0078D4',
    category: 'cloud',
  },

  // Média & Divertissement
  youtube: {
    id: 'youtube',
    name: 'YouTube',
    url: 'https://youtube.com',
    icon: '▶️',
    color: '#FF0000',
    category: 'media',
  },
  // Musique
  spotify: {
    id: 'spotify',
    name: 'Spotify',
    url: 'https://open.spotify.com',
    icon: '🎵',
    color: '#1DB954',
    category: 'music',
  },
  ytmusic: {
    id: 'ytmusic',
    name: 'YouTube Music',
    url: 'https://music.youtube.com',
    icon: '🎶',
    color: '#FF0000',
    category: 'music',
  },
  deezer: {
    id: 'deezer',
    name: 'Deezer',
    url: 'https://www.deezer.com',
    icon: '🎧',
    color: '#A238FF',
    category: 'music',
  },
  appleMusic: {
    id: 'appleMusic',
    name: 'Apple Music',
    url: 'https://music.apple.com',
    icon: '🍎',
    color: '#FA243C',
    category: 'music',
  },
  amazonMusic: {
    id: 'amazonMusic',
    name: 'Amazon Music',
    url: 'https://music.amazon.com',
    icon: '🎼',
    color: '#00A8E1',
    category: 'music',
  },
  tidal: {
    id: 'tidal',
    name: 'Tidal',
    url: 'https://listen.tidal.com',
    icon: '🌊',
    color: '#000000',
    category: 'music',
  },
  qobuz: {
    id: 'qobuz',
    name: 'Qobuz',
    url: 'https://play.qobuz.com',
    icon: '🎚️',
    color: '#0070D8',
    category: 'music',
  },
  soundcloud: {
    id: 'soundcloud',
    name: 'SoundCloud',
    url: 'https://soundcloud.com',
    icon: '🔊',
    color: '#FF5500',
    category: 'music',
  },
  bandcamp: {
    id: 'bandcamp',
    name: 'Bandcamp',
    url: 'https://bandcamp.com',
    icon: '🎸',
    color: '#629AA9',
    category: 'music',
  },
  twitch: {
    id: 'twitch',
    name: 'Twitch',
    url: 'https://twitch.tv',
    icon: '🎮',
    color: '#9146FF',
    category: 'media',
  },
  netflix: {
    id: 'netflix',
    name: 'Netflix',
    url: 'https://netflix.com',
    icon: '🍿',
    color: '#E50914',
    category: 'media',
  },
  disneyplus: {
    id: 'disneyplus',
    name: 'Disney+',
    url: 'https://www.disneyplus.com',
    icon: '🏰',
    color: '#113CCF',
    category: 'media',
  },
  primevideo: {
    id: 'primevideo',
    name: 'Prime Video',
    url: 'https://www.primevideo.com',
    icon: '🎬',
    color: '#00A8E1',
    category: 'media',
  },
  max: {
    id: 'max',
    name: 'Max (HBO)',
    url: 'https://play.max.com',
    icon: '🎞️',
    color: '#0046FF',
    category: 'media',
  },
  appletv: {
    id: 'appletv',
    name: 'Apple TV+',
    url: 'https://tv.apple.com',
    icon: '🍏',
    color: '#000000',
    category: 'media',
  },
  crunchyroll: {
    id: 'crunchyroll',
    name: 'Crunchyroll',
    url: 'https://www.crunchyroll.com',
    icon: '🍥',
    color: '#F47521',
    category: 'media',
  },
  paramountplus: {
    id: 'paramountplus',
    name: 'Paramount+',
    url: 'https://www.paramountplus.com',
    icon: '⛰️',
    color: '#0064FF',
    category: 'media',
  },
  canalplus: {
    id: 'canalplus',
    name: 'myCANAL',
    url: 'https://www.canalplus.com',
    icon: '📺',
    color: '#000000',
    category: 'media',
  },
  molotov: {
    id: 'molotov',
    name: 'Molotov',
    url: 'https://www.molotov.tv',
    icon: '🍸',
    color: '#F5064E',
    category: 'media',
  },
  plex: {
    id: 'plex',
    name: 'Plex',
    url: 'https://app.plex.tv',
    icon: '🎥',
    color: '#E5A00D',
    category: 'media',
  },
  dailymotion: {
    id: 'dailymotion',
    name: 'Dailymotion',
    url: 'https://www.dailymotion.com',
    icon: '▶️',
    color: '#0066DC',
    category: 'media',
  },

  // VPN (tableau de bord / compte — le routage se règle dans Réglages → Réseau)
  nordvpn: {
    id: 'nordvpn',
    name: 'NordVPN',
    url: 'https://my.nordaccount.com',
    icon: '🛡️',
    color: '#4687FF',
    category: 'vpn',
  },
  protonvpn: {
    id: 'protonvpn',
    name: 'Proton VPN',
    url: 'https://account.protonvpn.com',
    icon: '🔒',
    color: '#6D4AFF',
    category: 'vpn',
  },
  expressvpn: {
    id: 'expressvpn',
    name: 'ExpressVPN',
    url: 'https://www.expressvpn.com/sign-in',
    icon: '🚄',
    color: '#DA3940',
    category: 'vpn',
  },
  surfshark: {
    id: 'surfshark',
    name: 'Surfshark',
    url: 'https://my.surfshark.com',
    icon: '🦈',
    color: '#178A7E',
    category: 'vpn',
  },
  mullvad: {
    id: 'mullvad',
    name: 'Mullvad',
    url: 'https://mullvad.net/account',
    icon: '🐹',
    color: '#294D73',
    category: 'vpn',
  },
  windscribe: {
    id: 'windscribe',
    name: 'Windscribe',
    url: 'https://windscribe.com/myaccount',
    icon: '🌬️',
    color: '#4CA7DE',
    category: 'vpn',
  },
  cyberghost: {
    id: 'cyberghost',
    name: 'CyberGhost',
    url: 'https://my.cyberghostvpn.com',
    icon: '👻',
    color: '#FFCC00',
    category: 'vpn',
  },
  pia: {
    id: 'pia',
    name: 'Private Internet Access',
    url: 'https://www.privateinternetaccess.com/account',
    icon: '🕵️',
    color: '#6DC862',
    category: 'vpn',
  },

  // Éducation & Référence
  translate: {
    id: 'translate',
    name: 'Google Translate',
    url: 'https://translate.google.com',
    icon: '🔤',
    color: '#4285F4',
    category: 'reference',
    brandIcon: 'https://ssl.gstatic.com/images/branding/product/2x/translate_48dp.png',
  },
  maps: {
    id: 'maps',
    name: 'Google Maps',
    url: 'https://maps.google.com',
    icon: '🗺️',
    color: '#34A853',
    category: 'reference',
    brandIcon: 'https://ssl.gstatic.com/images/branding/product/2x/maps_48dp.png',
  },
  news: {
    id: 'news',
    name: 'Google News',
    url: 'https://news.google.com',
    icon: '📰',
    color: '#4285F4',
    category: 'media',
    brandIcon: 'https://ssl.gstatic.com/images/branding/product/2x/news_48dp.png',
  },
  classroom: {
    id: 'classroom',
    name: 'Google Classroom',
    url: 'https://classroom.google.com',
    icon: '🎓',
    color: '#34A853',
    category: 'reference',
    brandIcon: 'https://ssl.gstatic.com/images/branding/product/2x/classroom_48dp.png',
  },
  earth: {
    id: 'earth',
    name: 'Google Earth',
    url: 'https://earth.google.com',
    icon: '🌏',
    color: '#4285F4',
    category: 'reference',
    brandIcon: 'https://ssl.gstatic.com/images/branding/product/2x/earth_48dp.png',
  },
  books: {
    id: 'books',
    name: 'Google Books',
    url: 'https://books.google.com',
    icon: '📚',
    color: '#4285F4',
    category: 'reference',
  },
  wikipedia: {
    id: 'wikipedia',
    name: 'Wikipedia',
    url: 'https://wikipedia.org',
    icon: '📚',
    color: '#000000',
    category: 'reference',
  },
  stackoverflow: {
    id: 'stackoverflow',
    name: 'Stack Overflow',
    url: 'https://stackoverflow.com',
    icon: '💡',
    color: '#F58025',
    category: 'reference',
  },
  medium: {
    id: 'medium',
    name: 'Medium',
    url: 'https://medium.com',
    icon: '📖',
    color: '#000000',
    category: 'reference',
  },
  devto: {
    id: 'devto',
    name: 'DEV Community',
    url: 'https://dev.to',
    icon: '👩💻',
    color: '#0A0A0A',
    category: 'reference',
  },

  // Finance
  stripe: {
    id: 'stripe',
    name: 'Stripe',
    url: 'https://dashboard.stripe.com',
    icon: '💳',
    color: '#635BFF',
    category: 'finance',
  },
  paypal: {
    id: 'paypal',
    name: 'PayPal',
    url: 'https://paypal.com',
    icon: '💰',
    color: '#00457C',
    category: 'finance',
  },

  // Analytics
  analytics: {
    id: 'analytics',
    name: 'Google Analytics',
    url: 'https://analytics.google.com',
    icon: '📈',
    color: '#F9AB00',
    category: 'analytics',
  },
  plausible: {
    id: 'plausible',
    name: 'Plausible',
    url: 'https://plausible.io',
    icon: '📊',
    color: '#5850EC',
    category: 'analytics',
  },

  // CRM
  hubspot: {
    id: 'hubspot',
    name: 'HubSpot',
    url: 'https://app.hubspot.com',
    icon: '🎯',
    color: '#FF7A59',
    category: 'crm',
  },
  salesforce: {
    id: 'salesforce',
    name: 'Salesforce',
    url: 'https://salesforce.com',
    icon: '☁️',
    color: '#00A1E0',
    category: 'crm',
  },

  // Autres
  calendly: {
    id: 'calendly',
    name: 'Calendly',
    url: 'https://calendly.com',
    icon: '📅',
    color: '#006BFF',
    category: 'productivity',
  },
  miro: {
    id: 'miro',
    name: 'Miro',
    url: 'https://miro.com',
    icon: '🎨',
    color: '#FFD02F',
    category: 'productivity',
  },
  canva: {
    id: 'canva',
    name: 'Canva',
    url: 'https://canva.com',
    icon: '🖼️',
    color: '#00C4CC',
    category: 'design',
  },
};

export const categories = {
  communication: { name: 'Communication', icon: '💬', color: '#6366f1' },
  productivity: { name: 'Productivité', icon: '⚡', color: '#10b981' },
  development: { name: 'Développement', icon: '💻', color: '#8b5cf6' },
  ai: { name: 'IA & Chat', icon: '🤖', color: '#ec4899' },
  social: { name: 'Réseaux sociaux', icon: '🌐', color: '#3b82f6' },
  cloud: { name: 'Cloud & Storage', icon: '☁️', color: '#06b6d4' },
  music: { name: 'Musique', icon: '🎵', color: '#1DB954' },
  media: { name: 'Vidéo & Streaming', icon: '🎬', color: '#f59e0b' },
  vpn: { name: 'VPN', icon: '🛡️', color: '#4687FF' },
  reference: { name: 'Référence', icon: '📚', color: '#6b7280' },
  finance: { name: 'Finance', icon: '💰', color: '#14b8a6' },
  analytics: { name: 'Analytics', icon: '📊', color: '#a855f7' },
  crm: { name: 'CRM', icon: '🎯', color: '#ef4444' },
  design: { name: 'Design', icon: '🎨', color: '#f97316' },
};
